/* Yet Another Forum.NET Firebird data layer by vzrus
 * Copyright (C) 2006-2012 Vladimir Zakharov
 * https://github.com/vzrus
 * http://sourceforge.net/projects/yaf-datalayers/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2 only
 * General class structure is based on MS SQL Server code,
 * created by YAF developers
 *
 * http://www.yetanotherforum.net/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation;version 2 only
 * of the License.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
EXECUTE BLOCK
AS
BEGIN
-- Source foreign key: FK_objQual_ACCESSMASK_BOARD
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_ACCESSMASK_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_ACCESSMASK')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_ACCESSMASK ADD CONSTRAINT FK_objQual_ACCESSMASK_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source foreign key: FK_objQual_ACTIVE_BOARD
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_ACTIVE_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_ACTIVE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_ACTIVE ADD CONSTRAINT FK_objQual_ACTIVE_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


EXECUTE BLOCK
AS
BEGIN
-- Source foreign key: FK_objQual_ACTIVE_FORUM
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_ACTIVE_FORUM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_ACTIVE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_ACTIVE ADD CONSTRAINT FK_objQual_ACTIVE_FORUM FOREIGN KEY (FORUMID) REFERENCES objQual_FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_ACTIVE_TOPIC
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_ACTIVE_TOPIC') 
    AND (RC.RDB$RELATION_NAME = 'objQual_ACTIVE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_ACTIVE ADD CONSTRAINT FK_objQual_ACTIVE_TOPIC FOREIGN KEY (TOPICID) REFERENCES objQual_TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_ACTIVE_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_ACTIVE_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_ACTIVE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_ACTIVE ADD CONSTRAINT FK_objQual_ACTIVE_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_ATTACHMENT_MESSAGE

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_ATTACHMENT_MESSAGE') 
    AND (RC.RDB$RELATION_NAME = 'objQual_ATTACHMENT')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_ATTACHMENT ADD CONSTRAINT FK_objQual_ATTACHMENT_MESSAGE FOREIGN KEY (MESSAGEID) REFERENCES objQual_MESSAGE(MESSAGEID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_BANNEDIP_BOARDID
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_BANNEDIP_BOARDID') 
    AND (RC.RDB$RELATION_NAME = 'objQual_BANNEDIP')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_BANNEDIP ADD CONSTRAINT FK_objQual_BANNEDIP_BOARDID FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_BBCODE_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_BBCODE_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_BBCODE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_BBCODE ADD CONSTRAINT FK_objQual_BBCODE_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_CATEGORY_BOARD

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_CATEGORY_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_CATEGORY')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_CATEGORY ADD CONSTRAINT FK_objQual_CATEGORY_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_CHECKEMAIL_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_CHECKEMAIL_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_CHECKEMAIL')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_CHECKEMAIL ADD CONSTRAINT FK_objQual_CHECKEMAIL_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: FK_objQual_CHOICE_POLL
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_CHOICE_POLL') 
    AND (RC.RDB$RELATION_NAME = 'objQual_CHOICE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_CHOICE ADD CONSTRAINT FK_objQual_CHOICE_POLL FOREIGN KEY (POLLID) REFERENCES objQual_POLL(POLLID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: FK_objQual_EVENTLOG_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_EVENTLOG_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_EVENTLOG')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_EVENTLOG ADD CONSTRAINT FK_objQual_EVENTLOG_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_EXTENSION_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_EXTENSION_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_EXTENSION')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_EXTENSION ADD CONSTRAINT FK_objQual_EXTENSION_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_FORUM_CATEGORY
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUM_CATEGORY') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUM ADD CONSTRAINT FK_objQual_FORUM_CATEGORY FOREIGN KEY (CATEGORYID) REFERENCES objQual_CATEGORY(CATEGORYID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_FORUM_FORUM
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUM_FORUM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUM ADD CONSTRAINT FK_objQual_FORUM_FORUM FOREIGN KEY (PARENTID) REFERENCES objQual_FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_FORUM_MESSAGE
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUM_MESSAGE') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUM ADD CONSTRAINT FK_objQual_FORUM_MESSAGE FOREIGN KEY (LASTMESSAGEID) REFERENCES objQual_MESSAGE(MESSAGEID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_FORUM_TOPIC
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUM_TOPIC') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUM ADD CONSTRAINT FK_objQual_FORUM_TOPIC FOREIGN KEY (LASTTOPICID) REFERENCES objQual_TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_FORUM_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUM_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUM ADD CONSTRAINT FK_objQual_FORUM_USER FOREIGN KEY (LASTUSERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


-- Source foreign key: FK_objQual_FORUMACCESS_MASKccessMask
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUMACCESS_MASK') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUMACCESS')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUMACCESS ADD CONSTRAINT FK_objQual_FORUMACCESS_MASK FOREIGN KEY (ACCESSMASKID) REFERENCES objQual_ACCESSMASK(ACCESSMASKID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_FORUMACCESS_FORUM
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUMACCESS_FORUM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUMACCESS')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUMACCESS ADD CONSTRAINT FK_objQual_FORUMACCESS_FORUM FOREIGN KEY (FORUMID) REFERENCES objQual_FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_FORUMACCESS_GROUP
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUMACCESS_GROUP') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUMACCESS')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUMACCESS ADD CONSTRAINT FK_objQual_FORUMACCESS_GROUP FOREIGN KEY (GROUPID) REFERENCES objQual_GROUP(GROUPID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_GROUP_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_GROUP_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_GROUP')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_GROUP ADD CONSTRAINT FK_objQual_GROUP_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


-- Source foreign key: FK_objQual_MESSAGE_MESID_REPLYTO
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_MESSAGE_MESID_REPLYTO') 
    AND (RC.RDB$RELATION_NAME = 'objQual_MESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_MESSAGE ADD CONSTRAINT FK_objQual_MESSAGE_MESID_REPLYTO FOREIGN KEY (REPLYTO) REFERENCES objQual_MESSAGE(MESSAGEID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_MESSAGE_TOPIC
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_MESSAGE_TOPIC') 
    AND (RC.RDB$RELATION_NAME = 'objQual_MESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_MESSAGE ADD CONSTRAINT FK_objQual_MESSAGE_TOPIC FOREIGN KEY (TOPICID) REFERENCES objQual_TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_MESSAGE_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_MESSAGE_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_MESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_MESSAGE ADD CONSTRAINT FK_objQual_MESSAGE_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: TR_AI_objQual_NNTPFORUM_FORUMum
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'TR_AI_objQual_NNTPFORUM_FORUM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_NNTPFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_NNTPFORUM ADD CONSTRAINT TR_AI_objQual_NNTPFORUM_FORUM FOREIGN KEY (FORUMID) REFERENCES objQual_FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: TR_AI_objQual_NNTPFORUM_NNTPSERVpServer
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'TR_AI_objQual_NNTPFORUM_NNTPSERV') 
    AND (RC.RDB$RELATION_NAME = 'objQual_NNTPFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_NNTPFORUM ADD CONSTRAINT TR_AI_objQual_NNTPFORUM_NNTPSERV FOREIGN KEY (NNTPSERVERID) REFERENCES objQual_NNTPSERVER(NNTPSERVERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


-- Source foreign key: FK_objQual_NNTPSERVER_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_NNTPSERVER_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_NNTPSERVER')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_NNTPSERVER ADD CONSTRAINT FK_objQual_NNTPSERVER_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


-- Source foreign key: FK_objQual_NNTPTOPIC_NNTPF
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_NNTPTOPIC_NNTPF') 
    AND (RC.RDB$RELATION_NAME = 'objQual_NNTPTOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_NNTPTOPIC ADD CONSTRAINT FK_objQual_NNTPTOPIC_NNTPF FOREIGN KEY (NNTPFORUMID) REFERENCES objQual_NNTPFORUM(NNTPFORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_NNTPTOPIC_TOPICic
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_NNTPTOPIC_TOPIC') 
    AND (RC.RDB$RELATION_NAME = 'objQual_NNTPTOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_NNTPTOPIC ADD CONSTRAINT FK_objQual_NNTPTOPIC_TOPIC FOREIGN KEY (TOPICID) REFERENCES objQual_TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: FK_objQual_PMESSAGE_USER1
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_PMESSAGE_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_PMESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_PMESSAGE ADD CONSTRAINT FK_objQual_PMESSAGE_USER FOREIGN KEY (FROMUSERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


-- Source foreign key: FK_objQual_POLLVOTE_POLL
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_POLLVOTE_POLL') 
    AND (RC.RDB$RELATION_NAME = 'objQual_POLLVOTE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_POLLVOTE ADD CONSTRAINT FK_objQual_POLLVOTE_POLL FOREIGN KEY (POLLID) REFERENCES objQual_POLL(POLLID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: FK_objQual_RANK_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_RANK_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_RANK')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_RANK ADD CONSTRAINT FK_objQual_RANK_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: FK_objQual_REGISTRY_BOARDd
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_REGISTRY_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_REGISTRY')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_REGISTRY ADD CONSTRAINT FK_objQual_REGISTRY_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO


-- Source foreign key: FK_objQual_SMILEY_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_SMILEY_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_SMILEY')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_SMILEY ADD CONSTRAINT FK_objQual_SMILEY_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


-- Source foreign key: FK_objQual_TOPIC_FORUM
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_TOPIC_FORUM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_TOPIC ADD CONSTRAINT FK_objQual_TOPIC_FORUM FOREIGN KEY (FORUMID) REFERENCES objQual_FORUM(FORUMID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_TOPIC_MESSAGE
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_TOPIC_MESSAGE') 
    AND (RC.RDB$RELATION_NAME = 'objQual_TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_TOPIC ADD CONSTRAINT FK_objQual_TOPIC_MESSAGE FOREIGN KEY (LASTMESSAGEID) REFERENCES objQual_MESSAGE(MESSAGEID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_TOPIC_POLL
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_TOPIC_POLL') 
    AND (RC.RDB$RELATION_NAME = 'objQual_TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_TOPIC ADD CONSTRAINT FK_objQual_TOPIC_POLL FOREIGN KEY (POLLID) REFERENCES objQual_POLLGROUPCLUSTER(POLLGROUPID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_TOPIC_TOPIC
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_TOPIC_TOPIC') 
    AND (RC.RDB$RELATION_NAME = 'objQual_TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_TOPIC ADD CONSTRAINT FK_objQual_TOPIC_TOPIC FOREIGN KEY (TOPICMOVEDID) REFERENCES objQual_TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_TOPIC_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_TOPIC_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_TOPIC ADD CONSTRAINT FK_objQual_TOPIC_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_TOPIC_USER_2
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_TOPIC_USER_2') 
    AND (RC.RDB$RELATION_NAME = 'objQual_TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_TOPIC ADD CONSTRAINT FK_objQual_TOPIC_USER_2 FOREIGN KEY (LASTUSERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_USER_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USER_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USER')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USER ADD CONSTRAINT FK_objQual_USER_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_USER_RANK
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USER_RANK') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USER')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USER ADD CONSTRAINT FK_objQual_USER_RANK FOREIGN KEY (RANKID) REFERENCES objQual_RANK(RANKID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: FK_objQual_USERFORUM_ACCMessMask
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USERFORUM_ACCM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USERFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USERFORUM ADD CONSTRAINT FK_objQual_USERFORUM_ACCM FOREIGN KEY (ACCESSMASKID) REFERENCES objQual_ACCESSMASK(ACCESSMASKID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_USERFORUM_FORUMum
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USERFORUM_FORUM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USERFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USERFORUM ADD CONSTRAINT FK_objQual_USERFORUM_FORUM FOREIGN KEY (FORUMID) REFERENCES objQual_FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_USERFORUM_USERr
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USERFORUM_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USERFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USERFORUM ADD CONSTRAINT FK_objQual_USERFORUM_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_USERGROUP_GROUPup
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USERGROUP_GROUP') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USERGROUP')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USERGROUP ADD CONSTRAINT FK_objQual_USERGROUP_GROUP FOREIGN KEY (GROUPID) REFERENCES objQual_GROUP(GROUPID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_USERGROUP_USERr
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USERGROUP_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USERGROUP')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USERGROUP ADD CONSTRAINT FK_objQual_USERGROUP_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_USERPMESSAGE_PMPMessage
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USERPMESSAGE_PM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USERPMESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USERPMESSAGE ADD CONSTRAINT FK_objQual_USERPMESSAGE_PM FOREIGN KEY (PMESSAGEID) REFERENCES objQual_PMESSAGE(PMESSAGEID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_USERPMESSAGE_PMUser
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USERPMESSAGE_PMU') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USERPMESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USERPMESSAGE ADD CONSTRAINT FK_objQual_USERPMESSAGE_PMU FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: FK_objQual_WATCHFORUM1_FORUM
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_WATCHFORUM1_FORUM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_WATCHFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_WATCHFORUM ADD CONSTRAINT FK_objQual_WATCHFORUM1_FORUM FOREIGN KEY (FORUMID) REFERENCES objQual_FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_WatchForum1_objQual_User
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_WATCHFORUM1_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_WATCHFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_WATCHFORUM ADD CONSTRAINT FK_objQual_WATCHFORUM1_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO



-- Source foreign key: FK_objQual_WATCHTOPIC_TOPIC
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_WATCHTOPIC_TOPIC') 
    AND (RC.RDB$RELATION_NAME = 'objQual_WATCHTOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_WATCHTOPIC ADD CONSTRAINT FK_objQual_WATCHTOPIC_TOPIC FOREIGN KEY (TOPICID) REFERENCES objQual_TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_WatchTopic_objQual_User
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_WATCHTOPIC_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_WATCHTOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_WATCHTOPIC ADD CONSTRAINT FK_objQual_WATCHTOPIC_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


-- Source foreign key: FK_objQual_MSGHIS_MSGHISID
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_MSGHIS_MSGHISID') 
    AND (RC.RDB$RELATION_NAME = 'objQual_MESSAGEHISTORY')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_MESSAGEHISTORY 
   ADD CONSTRAINT FK_objQual_MSGHIS_MSGHISID 
   FOREIGN KEY (MESSAGEID) REFERENCES objQual_MESSAGE(MESSAGEID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USRPROF_USRID') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USERPROFILE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USERPROFILE 
   ADD CONSTRAINT FK_objQual_USRPROF_USRID 
   FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_MSGREPAUD_MSGREP') 
    AND (RC.RDB$RELATION_NAME = 'objQual_MESSAGEREPORTEDAUDIT')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_MESSAGEREPORTEDAUDIT 
   ADD CONSTRAINT FK_objQual_MSGREPAUD_MSGREP 
   FOREIGN KEY (MESSAGEID) REFERENCES objQual_MESSAGEREPORTED(MESSAGEID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUMREADTRACKING_USERID') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUMREADTRACKING')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUMREADTRACKING 
   ADD CONSTRAINT FK_objQual_FORUMREADTRACKING_USERID 
   FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUMREADTRACKING_FRMID') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUMREADTRACKING')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUMREADTRACKING 
   ADD CONSTRAINT FK_objQual_FORUMREADTRACKING_FRMID 
   FOREIGN KEY (FORUMID) REFERENCES objQual_FORUM(FORUMID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_TOPICREADTRACKING_TOPID') 
    AND (RC.RDB$RELATION_NAME = 'objQual_TOPICREADTRACKING')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_TOPICREADTRACKING 
   ADD CONSTRAINT FK_objQual_TOPICREADTRACKING_TOPID 
   FOREIGN KEY (TOPICID) REFERENCES objQual_TOPIC(TOPICID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUMREADTRACKING_FRMID') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUMREADTRACKING')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUMREADTRACKING 
   ADD CONSTRAINT FK_objQual_FORUMREADTRACKING_FRMID 
   FOREIGN KEY (FORUMID) REFERENCES objQual_FORUM(FORUMID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO


EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_REPUTATIONVOTE_FROMUSER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_REPUTATIONVOTE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_REPUTATIONVOTE 
   ADD CONSTRAINT FK_objQual_REPUTATIONVOTE_FROMUSER 
   FOREIGN KEY (REPUTATIONFROMUSERID) REFERENCES objQual_USER(USERID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_REPUTATIONVOTE_TOUSER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_REPUTATIONVOTE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_REPUTATIONVOTE 
   ADD CONSTRAINT FK_objQual_REPUTATIONVOTE_TOUSER 
   FOREIGN KEY (REPUTATIONTOUSERID) REFERENCES objQual_USER(USERID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_ADMPGUSRACCESS_USERID') 
    AND (RC.RDB$RELATION_NAME = 'objQual_ADMINPAGEUSERACCESS')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_ADMINPAGEUSERACCESS 
   ADD CONSTRAINT FK_objQual_ADMPGUSRACCESS_USERID 
   FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_ELOGGROUPACCESS_GROUPID') 
    AND (RC.RDB$RELATION_NAME = 'objQual_EVENTLOGGROUPACCESS')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_EVENTLOGGROUPACCESS 
   ADD CONSTRAINT FK_objQual_ELOGGROUPACCESS_GROUPID 
   FOREIGN KEY (GROUPID) REFERENCES objQual_GROUP(GROUPID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO


