/* Yet Another Forum.NET MySQL data layer by vzrus
 * Copyright (C) 2006-2012 Vladimir Zakharov
 * https://github.com/vzrus
 * http://sourceforge.net/projects/yaf-datalayers/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2 only
 * General class structure is based on MS SQL Server code,
 * created by YAF developers
 *
 * http://www.yetanotherforum.net/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation;version 2 only
 * of the License.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
EXECUTE BLOCK
AS
BEGIN
-- Source foreign key: FK_objQual_ACCESSMASK_BOARD
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_ACCESSMASK_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_ACCESSMASK')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_ACCESSMASK ADD CONSTRAINT FK_objQual_ACCESSMASK_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_ACCESS_ACCESSMASKID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_ACCESS_ACCESSMASKID FOR objQual_ACCESSMASK
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.ACCESSMASKID IS NULL) THEN
  NEW.ACCESSMASKID = GEN_ID(SEQ_objQual_ACCESSMASK_ACCESSMASKID, 1);
END;';
END
--GO



EXECUTE BLOCK
AS
BEGIN
-- Source foreign key: FK_objQual_ACTIVE_BOARD
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_ACTIVE_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_ACTIVE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_ACTIVE ADD CONSTRAINT FK_objQual_ACTIVE_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


EXECUTE BLOCK
AS
BEGIN
-- Source foreign key: FK_objQual_ACTIVE_FORUM
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_ACTIVE_FORUM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_ACTIVE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_ACTIVE ADD CONSTRAINT FK_objQual_ACTIVE_FORUM FOREIGN KEY (FORUMID) REFERENCES objQual_FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_ACTIVE_TOPIC
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_ACTIVE_TOPIC') 
    AND (RC.RDB$RELATION_NAME = 'objQual_ACTIVE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_ACTIVE ADD CONSTRAINT FK_objQual_ACTIVE_TOPIC FOREIGN KEY (TOPICID) REFERENCES objQual_TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_ACTIVE_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_ACTIVE_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_ACTIVE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_ACTIVE ADD CONSTRAINT FK_objQual_ACTIVE_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_ATTACHMENT_MESSAGE

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_ATTACHMENT_MESSAGE') 
    AND (RC.RDB$RELATION_NAME = 'objQual_ATTACHMENT')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_ATTACHMENT ADD CONSTRAINT FK_objQual_ATTACHMENT_MESSAGE FOREIGN KEY (MESSAGEID) REFERENCES objQual_MESSAGE(MESSAGEID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO


EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_ATTACH_ATTACHMENTID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_ATTACH_ATTACHMENTID FOR objQual_ATTACHMENT
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.ATTACHMENTID IS NULL) THEN
  NEW.ATTACHMENTID = GEN_ID(SEQ_objQual_ATTACHMENT_ATTACHMENTID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_BANNEDIP_BOARDID
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_BANNEDIP_BOARDID') 
    AND (RC.RDB$RELATION_NAME = 'objQual_BANNEDIP')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_BANNEDIP ADD CONSTRAINT FK_objQual_BANNEDIP_BOARDID FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_BANNEDIP_ID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_BANNEDIP_ID FOR objQual_BANNEDIP
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.ID IS NULL) THEN
  NEW.ID = GEN_ID(SEQ_objQual_BANNEDIP_ID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_BBCODE_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_BBCODE_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_BBCODE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_BBCODE ADD CONSTRAINT FK_objQual_BBCODE_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO
EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_BBCODE_BBCODEID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_BBCODE_BBCODEID FOR objQual_BBCODE
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.BBCODEID IS NULL) THEN
  NEW.BBCODEID = GEN_ID(SEQ_objQual_BBCODE_BBCODEID, 1);
END;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_BOARD_BOARDID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_BOARD_BOARDID FOR objQual_BOARD
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.BOARDID IS NULL) THEN
  NEW.BOARDID = GEN_ID(SEQ_objQual_BOARD_BOARDID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_CATEGORY_BOARD

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_CATEGORY_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_CATEGORY')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_CATEGORY ADD CONSTRAINT FK_objQual_CATEGORY_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_CATEGORY_CATEGORYID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_CATEGORY_CATEGORYID FOR objQual_CATEGORY
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.CATEGORYID IS NULL) THEN
  NEW.CATEGORYID = GEN_ID(SEQ_objQual_CATEGORY_CATEGORYID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_CHECKEMAIL_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_CHECKEMAIL_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_CHECKEMAIL')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_CHECKEMAIL ADD CONSTRAINT FK_objQual_CHECKEMAIL_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_CHEKE_CHECKEMAILID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_CHEKE_CHECKEMAILID FOR objQual_CHECKEMAIL
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.CHECKEMAILID IS NULL) THEN
  NEW.CHECKEMAILID = GEN_ID(SEQ_objQual_CHECKEMAIL_CHECKEMAILID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_CHOICE_POLL
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_CHOICE_POLL') 
    AND (RC.RDB$RELATION_NAME = 'objQual_CHOICE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_CHOICE ADD CONSTRAINT FK_objQual_CHOICE_POLL FOREIGN KEY (POLLID) REFERENCES objQual_POLL(POLLID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_CHOICE_CHOICEID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_CHOICE_CHOICEID FOR objQual_CHOICE
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.CHOICEID IS NULL) THEN
  NEW.CHOICEID = GEN_ID(SEQ_objQual_CHOICE_CHOICEID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_EVENTLOG_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_EVENTLOG_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_EVENTLOG')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_EVENTLOG ADD CONSTRAINT FK_objQual_EVENTLOG_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_EVENTLOG_EVENTLOGID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_EVENTLOG_EVENTLOGID FOR objQual_EVENTLOG
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.EVENTLOGID IS NULL) THEN
  NEW.EVENTLOGID = GEN_ID(SEQ_objQual_EVENTLOG_EVENTLOGID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_EXTENSION_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_EXTENSION_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_EXTENSION')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_EXTENSION ADD CONSTRAINT FK_objQual_EXTENSION_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_EXTENSION_EXTENSIONID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_EXTENSION_EXTENSIONID FOR objQual_EXTENSION
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.EXTENSIONID IS NULL) THEN
  NEW.EXTENSIONID = GEN_ID(SEQ_objQual_EXTENSION_EXTENSIONID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_FORUM_CATEGORY
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUM_CATEGORY') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUM ADD CONSTRAINT FK_objQual_FORUM_CATEGORY FOREIGN KEY (CATEGORYID) REFERENCES objQual_CATEGORY(CATEGORYID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_FORUM_FORUM
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUM_FORUM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUM ADD CONSTRAINT FK_objQual_FORUM_FORUM FOREIGN KEY (PARENTID) REFERENCES objQual_FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_FORUM_MESSAGE
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUM_MESSAGE') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUM ADD CONSTRAINT FK_objQual_FORUM_MESSAGE FOREIGN KEY (LASTMESSAGEID) REFERENCES objQual_MESSAGE(MESSAGEID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_FORUM_TOPIC
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUM_TOPIC') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUM ADD CONSTRAINT FK_objQual_FORUM_TOPIC FOREIGN KEY (LASTTOPICID) REFERENCES objQual_TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_FORUM_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUM_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUM ADD CONSTRAINT FK_objQual_FORUM_USER FOREIGN KEY (LASTUSERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_FORUM_FORUMID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_FORUM_FORUMID FOR objQual_FORUM
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.FORUMID IS NULL) THEN
  NEW.FORUMID = GEN_ID(SEQ_objQual_FORUM_FORUMID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_FORUMACCESS_MASKccessMask
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUMACCESS_MASK') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUMACCESS')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUMACCESS ADD CONSTRAINT FK_objQual_FORUMACCESS_MASK FOREIGN KEY (ACCESSMASKID) REFERENCES objQual_ACCESSMASK(ACCESSMASKID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_FORUMACCESS_FORUM
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUMACCESS_FORUM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUMACCESS')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUMACCESS ADD CONSTRAINT FK_objQual_FORUMACCESS_FORUM FOREIGN KEY (FORUMID) REFERENCES objQual_FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_FORUMACCESS_GROUP
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_FORUMACCESS_GROUP') 
    AND (RC.RDB$RELATION_NAME = 'objQual_FORUMACCESS')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_FORUMACCESS ADD CONSTRAINT FK_objQual_FORUMACCESS_GROUP FOREIGN KEY (GROUPID) REFERENCES objQual_GROUP(GROUPID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_GROUP_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_GROUP_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_GROUP')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_GROUP ADD CONSTRAINT FK_objQual_GROUP_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'FK_objQual_GROUP_GROUPID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER FK_objQual_GROUP_GROUPID FOR objQual_GROUP
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.GROUPID IS NULL) THEN
  NEW.GROUPID = GEN_ID(SEQ_objQual_GROUP_GROUPID, 1);
END;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_MAIL_MAILID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_MAIL_MAILID FOR objQual_MAIL
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.MAILID IS NULL) THEN
  NEW.MAILID = GEN_ID(SEQ_objQual_MAIL_MAILID, 1);
END;';
END
--GO


EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_MEDAL_MEDALID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_MEDAL_MEDALID FOR objQual_MEDAL
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.MEDALID IS NULL) THEN
  NEW.MEDALID = GEN_ID(SEQ_objQual_MEDAL_MEDALID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_MESSAGE_MESID_REPLYTO
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_MESSAGE_MESID_REPLYTO') 
    AND (RC.RDB$RELATION_NAME = 'objQual_MESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_MESSAGE ADD CONSTRAINT FK_objQual_MESSAGE_MESID_REPLYTO FOREIGN KEY (REPLYTO) REFERENCES objQual_MESSAGE(MESSAGEID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_MESSAGE_TOPIC
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_MESSAGE_TOPIC') 
    AND (RC.RDB$RELATION_NAME = 'objQual_MESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_MESSAGE ADD CONSTRAINT FK_objQual_MESSAGE_TOPIC FOREIGN KEY (TOPICID) REFERENCES objQual_TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_MESSAGE_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_MESSAGE_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_MESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_MESSAGE ADD CONSTRAINT FK_objQual_MESSAGE_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_MESSAGE_MESSAGEID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_MESSAGE_MESSAGEID FOR objQual_MESSAGE
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.MESSAGEID IS NULL) THEN
  NEW.MESSAGEID = GEN_ID(SEQ_objQual_MESSAGE_MESSAGEID, 1);
END;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_MESSAG_LOGID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_MESSAG_LOGID FOR objQual_MESSAGEREPORTEDAUDIT
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.LOGID IS NULL) THEN
  NEW.LOGID = GEN_ID(SEQ_objQual_MESSAGE_LOGID, 1);
END;';
END
--GO

-- Source foreign key: TR_AI_objQual_NNTPFORUM_FORUMum
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'TR_AI_objQual_NNTPFORUM_FORUM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_NNTPFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_NNTPFORUM ADD CONSTRAINT TR_AI_objQual_NNTPFORUM_FORUM FOREIGN KEY (FORUMID) REFERENCES objQual_FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: TR_AI_objQual_NNTPFORUM_NNTPSERVpServer
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'TR_AI_objQual_NNTPFORUM_NNTPSERV') 
    AND (RC.RDB$RELATION_NAME = 'objQual_NNTPFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_NNTPFORUM ADD CONSTRAINT TR_AI_objQual_NNTPFORUM_NNTPSERV FOREIGN KEY (NNTPSERVERID) REFERENCES objQual_NNTPSERVER(NNTPSERVERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_NNTPFORUM_NNTPFORUMID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_NNTPFORUM_NNTPFORUMID FOR objQual_NNTPFORUM
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.NNTPFORUMID IS NULL) THEN
  NEW.NNTPFORUMID = GEN_ID(SEQ_objQual_NNTPFORUM_NNTPFORUMID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_NNTPSERVER_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_NNTPSERVER_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_NNTPSERVER')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_NNTPSERVER ADD CONSTRAINT FK_objQual_NNTPSERVER_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_NNTPSE_NNTPSERVERID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_NNTPSE_NNTPSERVERID FOR objQual_NNTPSERVER
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.NNTPSERVERID IS NULL) THEN
  NEW.NNTPSERVERID = GEN_ID(SEQ_objQual_NNTPSERVER_NNTPSERVERID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_NNTPTOPIC_NNTPF
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_NNTPTOPIC_NNTPF') 
    AND (RC.RDB$RELATION_NAME = 'objQual_NNTPTOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_NNTPTOPIC ADD CONSTRAINT FK_objQual_NNTPTOPIC_NNTPF FOREIGN KEY (NNTPFORUMID) REFERENCES objQual_NNTPFORUM(NNTPFORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_NNTPTOPIC_TOPICic
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_NNTPTOPIC_TOPIC') 
    AND (RC.RDB$RELATION_NAME = 'objQual_NNTPTOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_NNTPTOPIC ADD CONSTRAINT FK_objQual_NNTPTOPIC_TOPIC FOREIGN KEY (TOPICID) REFERENCES objQual_TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_NNTPTOPIC_NNTPTOPICID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_NNTPTOPIC_NNTPTOPICID FOR objQual_NNTPTOPIC
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.NNTPTOPICID IS NULL) THEN
  NEW.NNTPTOPICID = GEN_ID(SEQ_objQual_NNTPTOPIC_NNTPTOPICID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_PMESSAGE_USER1
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_PMESSAGE_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_PMESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_PMESSAGE ADD CONSTRAINT FK_objQual_PMESSAGE_USER FOREIGN KEY (FROMUSERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_PMESSAGE_PMESSAGEID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_PMESSAGE_PMESSAGEID FOR objQual_PMESSAGE
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.PMESSAGEID IS NULL) THEN
  NEW.PMESSAGEID = GEN_ID(SEQ_objQual_PMESSAGE_PMESSAGEID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_POLLVOTE_POLL
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_POLLVOTE_POLL') 
    AND (RC.RDB$RELATION_NAME = 'objQual_POLLVOTE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_POLLVOTE ADD CONSTRAINT FK_objQual_POLLVOTE_POLL FOREIGN KEY (POLLID) REFERENCES objQual_POLL(POLLID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_POLLVOTE_POLLVOTEID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_POLLVOTE_POLLVOTEID FOR objQual_POLLVOTE
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.POLLVOTEID IS NULL) THEN
  NEW.POLLVOTEID = GEN_ID(SEQ_objQual_POLLVOTE_POLLVOTEID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_RANK_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_RANK_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_RANK')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_RANK ADD CONSTRAINT FK_objQual_RANK_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_RANK_RANKID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_RANK_RANKID FOR objQual_RANK
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.RANKID IS NULL) THEN
  NEW.RANKID = GEN_ID(SEQ_objQual_RANK_RANKID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_REGISTRY_BOARDd
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_REGISTRY_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_REGISTRY')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_REGISTRY ADD CONSTRAINT FK_objQual_REGISTRY_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_REGISTRY_REGISTRYID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_REGISTRY_REGISTRYID FOR objQual_REGISTRY
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.REGISTRYID IS NULL) THEN
  NEW.REGISTRYID = GEN_ID(SEQ_objQual_REGISTRY_REGISTRYID, 1);
END;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_REPLACE_WORDS_ID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_REPLACE_WORDS_ID FOR objQual_REPLACE_WORDS
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.ID IS NULL) THEN
  NEW.ID = GEN_ID(SEQ_objQual_REPLACE_WORDS_ID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_SMILEY_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_SMILEY_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_SMILEY')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_SMILEY ADD CONSTRAINT FK_objQual_SMILEY_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_SMILEY_SMILEYID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_SMILEY_SMILEYID FOR objQual_SMILEY
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.SMILEYID IS NULL) THEN
  NEW.SMILEYID = GEN_ID(SEQ_objQual_SMILEY_SMILEYID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_TOPIC_FORUM
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_TOPIC_FORUM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_TOPIC ADD CONSTRAINT FK_objQual_TOPIC_FORUM FOREIGN KEY (FORUMID) REFERENCES objQual_FORUM(FORUMID) ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_TOPIC_MESSAGE
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_TOPIC_MESSAGE') 
    AND (RC.RDB$RELATION_NAME = 'objQual_TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_TOPIC ADD CONSTRAINT FK_objQual_TOPIC_MESSAGE FOREIGN KEY (LASTMESSAGEID) REFERENCES objQual_MESSAGE(MESSAGEID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_TOPIC_POLL
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_TOPIC_POLL') 
    AND (RC.RDB$RELATION_NAME = 'objQual_TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_TOPIC ADD CONSTRAINT FK_objQual_TOPIC_POLL FOREIGN KEY (POLLID) REFERENCES objQual_POLLGROUPCLUSTER(POLLGROUPID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_TOPIC_TOPIC
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_TOPIC_TOPIC') 
    AND (RC.RDB$RELATION_NAME = 'objQual_TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_TOPIC ADD CONSTRAINT FK_objQual_TOPIC_TOPIC FOREIGN KEY (TOPICMOVEDID) REFERENCES objQual_TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_TOPIC_USER
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_TOPIC_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_TOPIC ADD CONSTRAINT FK_objQual_TOPIC_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_TOPIC_USER_2
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_TOPIC_USER_2') 
    AND (RC.RDB$RELATION_NAME = 'objQual_TOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_TOPIC ADD CONSTRAINT FK_objQual_TOPIC_USER_2 FOREIGN KEY (LASTUSERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_TOPIC_TOPICID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_TOPIC_TOPICID FOR objQual_TOPIC
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.TOPICID IS NULL) THEN
  NEW.TOPICID = GEN_ID(SEQ_objQual_TOPIC_TOPICID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_USER_BOARD
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USER_BOARD') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USER')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USER ADD CONSTRAINT FK_objQual_USER_BOARD FOREIGN KEY (BOARDID) REFERENCES objQual_BOARD(BOARDID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_USER_RANK
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USER_RANK') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USER')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USER ADD CONSTRAINT FK_objQual_USER_RANK FOREIGN KEY (RANKID) REFERENCES objQual_RANK(RANKID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_USER_USERID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_USER_USERID FOR objQual_USER
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.USERID IS NULL) THEN
  NEW.USERID = GEN_ID(SEQ_objQual_USER_USERID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_USERFORUM_ACCMessMask
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USERFORUM_ACCM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USERFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USERFORUM ADD CONSTRAINT FK_objQual_USERFORUM_ACCM FOREIGN KEY (ACCESSMASKID) REFERENCES objQual_ACCESSMASK(ACCESSMASKID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_USERFORUM_FORUMum
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USERFORUM_FORUM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USERFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USERFORUM ADD CONSTRAINT FK_objQual_USERFORUM_FORUM FOREIGN KEY (FORUMID) REFERENCES objQual_FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_USERFORUM_USERr
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USERFORUM_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USERFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USERFORUM ADD CONSTRAINT FK_objQual_USERFORUM_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_USERGROUP_GROUPup
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USERGROUP_GROUP') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USERGROUP')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USERGROUP ADD CONSTRAINT FK_objQual_USERGROUP_GROUP FOREIGN KEY (GROUPID) REFERENCES objQual_GROUP(GROUPID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_USERGROUP_USERr
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USERGROUP_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USERGROUP')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USERGROUP ADD CONSTRAINT FK_objQual_USERGROUP_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_USERPMESSAGE_PMPMessage
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USERPMESSAGE_PM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USERPMESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USERPMESSAGE ADD CONSTRAINT FK_objQual_USERPMESSAGE_PM FOREIGN KEY (PMESSAGEID) REFERENCES objQual_PMESSAGE(PMESSAGEID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_USERPMESSAGE_PMUser
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USERPMESSAGE_PMU') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USERPMESSAGE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USERPMESSAGE ADD CONSTRAINT FK_objQual_USERPMESSAGE_PMU FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_USERPM_USERPMESSAGEID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_USERPM_USERPMESSAGEID FOR objQual_USERPMESSAGE
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.USERPMESSAGEID IS NULL) THEN
  NEW.USERPMESSAGEID = GEN_ID(SEQ_objQual_USERPME_USERPMESSAGEID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_WATCHFORUM1_FORUM
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_WATCHFORUM1_FORUM') 
    AND (RC.RDB$RELATION_NAME = 'objQual_WATCHFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_WATCHFORUM ADD CONSTRAINT FK_objQual_WATCHFORUM1_FORUM FOREIGN KEY (FORUMID) REFERENCES objQual_FORUM(FORUMID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_WatchForum1_objQual_User
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_WATCHFORUM1_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_WATCHFORUM')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_WATCHFORUM ADD CONSTRAINT FK_objQual_WATCHFORUM1_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_WATCHF_WATCHFORUMID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_WATCHF_WATCHFORUMID FOR objQual_WATCHFORUM
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.WATCHFORUMID IS NULL) THEN
  NEW.WATCHFORUMID = GEN_ID(SEQ_objQual_WATCHFORUM_WATCHFORUMID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_WATCHTOPIC_TOPIC
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_WATCHTOPIC_TOPIC') 
    AND (RC.RDB$RELATION_NAME = 'objQual_WATCHTOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_WATCHTOPIC ADD CONSTRAINT FK_objQual_WATCHTOPIC_TOPIC FOREIGN KEY (TOPICID) REFERENCES objQual_TOPIC(TOPICID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

-- Source foreign key: FK_objQual_WatchTopic_objQual_User
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_WATCHTOPIC_USER') 
    AND (RC.RDB$RELATION_NAME = 'objQual_WATCHTOPIC')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_WATCHTOPIC ADD CONSTRAINT FK_objQual_WATCHTOPIC_USER FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS(
    SELECT 1 FROM RDB$TRIGGERS T
    WHERE T.RDB$TRIGGER_NAME = 'TR_AI_objQual_WATCHT_WATCHTOPICID' 
  )) THEN  
EXECUTE STATEMENT 'CREATE TRIGGER TR_AI_objQual_WATCHT_WATCHTOPICID FOR objQual_WATCHTOPIC
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
IF (NEW.WATCHTOPICID IS NULL) THEN
  NEW.WATCHTOPICID = GEN_ID(SEQ_objQual_WATCHTOPIC_WATCHTOPICID, 1);
END;';
END
--GO

-- Source foreign key: FK_objQual_MSGHIS_MSGHISID
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_MSGHIS_MSGHISID') 
    AND (RC.RDB$RELATION_NAME = 'objQual_MESSAGEHISTORY')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_MESSAGEHISTORY 
   ADD CONSTRAINT FK_objQual_MSGHIS_MSGHISID 
   FOREIGN KEY (MESSAGEID) REFERENCES objQual_MESSAGE(MESSAGEID) 
   ON DELETE NO ACTION ON UPDATE NO ACTION;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS RC
    WHERE (RC.RDB$CONSTRAINT_NAME = 'FK_objQual_USRPROF_USRID') 
    AND (RC.RDB$RELATION_NAME = 'objQual_USERPROFILE')
        AND (RC.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY')
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE objQual_USERPROFILE 
   ADD CONSTRAINT FK_objQual_USRPROF_USRID 
   FOREIGN KEY (USERID) REFERENCES objQual_USER(USERID) 
   ON DELETE CASCADE ON UPDATE NO ACTION;';
END
--GO


