
/* Yet Another Forum.NET Firebird data layer by vzrus
 * Copyright (C) 2006-2012 Vladimir Zakharov
 * https://github.com/vzrus
 * http://sourceforge.net/projects/yaf-datalayers/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2 only
 * General class structure is based on MS SQL Server code,
 * created by YAF developers
 *
 * http://www.yetanotherforum.net/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation;version 2 only
 * of the License.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BITSET')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BITSET;';
END

--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_POSTS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_POSTS;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_TOPICS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_TOPICS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_LASTTOPIC')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_LASTTOPIC';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MEDAL_GETRIBBONSETTINGS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MEDAL_GETRIBBONSETTINGS';
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MEDAL_GETSORTORDER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MEDAL_GETSORTORDER';
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MEDAL_HIDE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MEDAL_HIDE';
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_LASTPOSTED')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_LASTPOSTED';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_GET_USERSTYLE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_GET_USERSTYLE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_GETTHANKSINFO')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_GETTHANKSINFO';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_SAVE_PARENTSCHECKER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_SAVE_PARENTSCHECKER';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_REGISTRY_VALUE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_REGISTRY_VALUE';
END
--GO







