/* Yet Another Forum.NET Firebird data layer by vzrus
 * Copyright (C) 2006-2012 Vladimir Zakharov
 * https://github.com/vzrus
 * http://sourceforge.net/projects/yaf-datalayers/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2 only
 * General class structure is based on MS SQL Server code,
 * created by YAF developers
 *
 * http://www.yetanotherforum.net/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation;version 2 only
 * of the License.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
EXECUTE BLOCK
AS
BEGIN
-- Source Index: IX_objQual_CATEGORY_BOARDID
  IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_CATEGORY_BOARDID') AND (I.RDB$RELATION_NAME = 'objQual_CATEGORY')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_CATEGORY_BOARDID ON objQual_CATEGORY(BOARDID);';
  END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source Index: IX_objQual_CATEGORY_NAME
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_CATEGORY_NAME') AND (I.RDB$RELATION_NAME = 'objQual_CATEGORY')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_CATEGORY_NAME ON objQual_CATEGORY(NAME);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_FORUM_CATEGORYID
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_FORUM_CATEGORYID') AND (I.RDB$RELATION_NAME = 'objQual_FORUM')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_FORUM_CATEGORYID ON objQual_FORUM(CATEGORYID);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_FORUM_FLAGS
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_FORUM_FLAGS') AND (I.RDB$RELATION_NAME = 'objQual_FORUM')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_FORUM_FLAGS ON objQual_FORUM(FLAGS);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_FORUM_PARENTID

 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_FORUM_PARENTID') AND (I.RDB$RELATION_NAME = 'objQual_FORUM')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_FORUM_PARENTID ON objQual_FORUM(PARENTID);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_ForumAccess_ForumID
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_FORUMACCESS_FORUM') AND (I.RDB$RELATION_NAME = 'objQual_FORUMACCESS')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_FORUMACCESS_FORUM ON objQual_FORUMACCESS(FORUMID);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_MESSAGE_FLAGS
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_MESSAGE_FLAGS') AND (I.RDB$RELATION_NAME = 'objQual_MESSAGE')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_MESSAGE_FLAGS ON objQual_MESSAGE(FLAGS);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_MESSAGE_TOPICID
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_MESSAGE_TOPICID') AND (I.RDB$RELATION_NAME = 'objQual_MESSAGE')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_MESSAGE_TOPICID ON objQual_MESSAGE(TOPICID);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_MESSAGE_USERID
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_MESSAGE_USERID') AND (I.RDB$RELATION_NAME = 'objQual_MESSAGE')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_MESSAGE_USERID ON objQual_MESSAGE(USERID);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_MESSAGE_USERID
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_MESSAGE_POSTED_D') AND (I.RDB$RELATION_NAME = 'objQual_MESSAGE')
   )) THEN
  EXECUTE STATEMENT 'CREATE DESC INDEX IX_objQual_MESSAGE_POSTED_D ON objQual_MESSAGE(POSTED);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_POLLVOTE_POLLID
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_POLLVOTE_POLLID') AND (I.RDB$RELATION_NAME = 'objQual_POLLVOTE')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_POLLVOTE_POLLID ON objQual_POLLVOTE(POLLID);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_POLLVOTE_REMOTEIP
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_POLLVOTE_REMOTEIP') AND (I.RDB$RELATION_NAME = 'objQual_POLLVOTE')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_POLLVOTE_REMOTEIP ON objQual_POLLVOTE(REMOTEIP);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_POLLVOTE_USERID
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_POLLVOTE_USERID') AND (I.RDB$RELATION_NAME = 'objQual_POLLVOTE')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_POLLVOTE_USERID ON objQual_POLLVOTE(USERID);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source Index: IX_objQual_REGISTRY_NAME
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_REGISTRY_NAME') AND (I.RDB$RELATION_NAME = 'objQual_REGISTRY')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_REGISTRY_NAME ON objQual_REGISTRY(BOARDID,NAME);';
 END
--GO


EXECUTE BLOCK
AS
BEGIN
-- Source Index: IX_objQual_REPUTATIONVOTE_FU_TU
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_REPUTATIONVOTE_FU_TU') AND (I.RDB$RELATION_NAME = 'objQual_REPUTATIONVOTE')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_REPUTATIONVOTE_FU_TU ON objQual_REPUTATIONVOTE(REPUTATIONFROMUSERID,REPUTATIONTOUSERID);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN


-- Source Index: IX_objQual_TOPIC_FLAGS
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_TOPIC_FLAGS') AND (I.RDB$RELATION_NAME = 'objQual_TOPIC')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_TOPIC_FLAGS ON objQual_TOPIC(FLAGS);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_TOPIC_FORUMID
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_TOPIC_FORUMID') AND (I.RDB$RELATION_NAME = 'objQual_TOPIC')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_TOPIC_FORUMID ON objQual_TOPIC(FORUMID);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_TOPIC_USERID
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_TOPIC_USERID') AND (I.RDB$RELATION_NAME = 'objQual_TOPIC')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_TOPIC_USERID ON objQual_TOPIC(USERID);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN


-- Source Index: IX_objQual_USER_FLAGS
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_USER_FLAGS') AND (I.RDB$RELATION_NAME = 'objQual_USER')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_USER_FLAGS ON objQual_USER(FLAGS);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_USER_NAME
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_USER_NAME') AND (I.RDB$RELATION_NAME = 'objQual_USER')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_USER_NAME ON objQual_USER(NAME);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_User_ProviderUserKey
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_USER_PROVIDERUSER') AND (I.RDB$RELATION_NAME = 'objQual_USER')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_USER_PROVIDERUSER ON objQual_USER(PROVIDERUSERKEY);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_USERGROUP_USERID
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_USERGROUP_USERID') AND (I.RDB$RELATION_NAME = 'objQual_USERGROUP')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_USERGROUP_USERID ON objQual_USERGROUP(USERID);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN

-- Source Index: IX_objQual_UserPMessage_UserID
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_USERPMESSAGE_USER') AND (I.RDB$RELATION_NAME = 'objQual_USERPMESSAGE')
   )) THEN
  EXECUTE STATEMENT 'CREATE INDEX IX_objQual_USERPMESSAGE_USER ON objQual_USERPMESSAGE(USERID);';
 END
--GO

-- IX_objQual_Thanks

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_THANKS_MESSAGEID') AND (I.RDB$RELATION_NAME = 'objQual_THANKS')
   )) THEN
  EXECUTE STATEMENT 'CREATE  INDEX IX_objQual_THANKS_MESSAGEID ON objQual_THANKS(MESSAGEID);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_THANKS_THANKSFRUSRID') AND (I.RDB$RELATION_NAME = 'objQual_THANKS')
   )) THEN
  EXECUTE STATEMENT 'CREATE  INDEX IX_objQual_THANKS_THANKSFRUSRID ON objQual_THANKS(THANKSFROMUSERID);';
 END
--GO

EXECUTE BLOCK
AS
BEGIN
 IF (NOT EXISTS (
    SELECT 1 FROM RDB$INDICES I
    WHERE (I.RDB$INDEX_NAME = 'IX_objQual_THANKS_THANKSTOUSRID') AND (I.RDB$RELATION_NAME = 'objQual_THANKS')
   )) THEN
  EXECUTE STATEMENT 'CREATE  INDEX IX_objQual_THANKS_THANKSTOUSRID ON objQual_THANKS(THANKSTOUSERID);';
 END
--GO



