/* Yet Another Forum.NET MySQL data layer by vzrus
 * Copyright (C) 2006-2012 Vladimir Zakharov
 * https://github.com/vzrus
 * http://sourceforge.net/projects/yaf-datalayers/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2 only
 * General class structure is based on MS SQL Server code,
 * created by YAF developers
 *
 * http://www.yetanotherforum.net/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation;version 2 only
 * of the License.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY001')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_ACCESSMASK DROP CONSTRAINT PRIMARY001;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY002')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_ACTIVE DROP CONSTRAINT PRIMARY002;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY003')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_ATTACHMENT DROP CONSTRAINT PRIMARY003;';
END
--GO

EXECUTE BLOCK
AS
BEGIN 
-- Source unique key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY004')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_BANNEDIP DROP CONSTRAINT PRIMARY004;';
END
--GO

EXECUTE BLOCK
AS
BEGIN 
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY005')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_BBCODE DROP CONSTRAINT PRIMARY005;';
END
--GO


EXECUTE BLOCK
AS
BEGIN 
-- Source unique key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY007')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_CATEGORY DROP CONSTRAINT PRIMARY007;';
END
--GO

EXECUTE BLOCK
AS
BEGIN 
-- Source unique key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY008')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_CHECKEMAIL DROP CONSTRAINT PRIMARY008;';
END
--GO

EXECUTE BLOCK
AS
BEGIN 
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY009')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_CHOICE DROP CONSTRAINT PRIMARY009;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY010')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_EVENTLOG DROP CONSTRAINT PRIMARY010;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY011')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_EXTENSION DROP CONSTRAINT PRIMARY011;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY012')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_FORUM DROP CONSTRAINT PRIMARY012;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY013')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_FORUMACCESS DROP CONSTRAINT PRIMARY013;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY014')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_GROUP DROP CONSTRAINT PRIMARY014;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY015')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_MAIL DROP CONSTRAINT PRIMARY015;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY016')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_MEDAL DROP CONSTRAINT PRIMARY016;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY017')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_MESSAGE DROP CONSTRAINT PRIMARY017;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY018')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_MESSAGEREPORTEDAUDIT DROP CONSTRAINT PRIMARY018;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY019')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_NNTPFORUM DROP CONSTRAINT PRIMARY019;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY020')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_NNTPSERVER DROP CONSTRAINT PRIMARY020;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY021')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_NNTPTOPIC DROP CONSTRAINT PRIMARY021;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY022')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_PMESSAGE DROP CONSTRAINT PRIMARY022;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY023')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_POLL DROP CONSTRAINT PRIMARY023;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY024')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_POLLVOTE DROP CONSTRAINT PRIMARY024;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY029')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_RANK DROP CONSTRAINT PRIMARY029;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY030')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_REGISTRY DROP CONSTRAINT PRIMARY030;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY031')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_REPLACE_WORDS DROP CONSTRAINT PRIMARY031;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PK_objQual_SHOUTBOXMESSAGE')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_SHOUTBOXMESSAGE DROP CONSTRAINT PK_objQual_SHOUTBOXMESSAGE;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY032')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_SMILEY DROP CONSTRAINT PRIMARY032;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY033')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_TOPIC DROP CONSTRAINT PRIMARY033;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY034')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_USER DROP CONSTRAINT PRIMARY034;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source Index: PK_YAF_IGNOREUSER_USERID
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PK_objQual_IGNOREUSER_USERID')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_IGNOREUSER DROP CONSTRAINT PK_objQual_IGNOREUSER_USERID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN 
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY035')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_USERFORUM DROP CONSTRAINT PRIMARY035;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY036')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_USERGROUP DROP CONSTRAINT PRIMARY036;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY037')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_USERPMESSAGE DROP CONSTRAINT PRIMARY037;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY038')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_WATCHFORUM DROP CONSTRAINT PRIMARY038;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: PRIMARY
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='IX_objQual_WATCHTOPIC')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_WATCHTOPIC DROP CONSTRAINT PRIMARY039;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: IX_objQual_BannedIP
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='IX_objQual_BANNEDIP')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_BANNEDIP DROP CONSTRAINT IX_objQual_BANNEDIP;';
END
--GO 

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: IX_objQual_Category
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='IX_objQual_CATEGORY')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_CATEGORY DROP CONSTRAINT IX_objQual_CATEGORY;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: IX_objQual_CheckEmail
IF (EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='IX_objQual_CHECKEMAIL')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_CHECKEMAIL DROP CONSTRAINT IX_objQual_CHECKEMAIL;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: IX_objQual_Forum
IF (EXISTS(SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='IX_objQual_FORUM')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_FORUM DROP CONSTRAINT IX_objQual_FORUM;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: IX_objQual_Group
IF (EXISTS(SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='IX_objQual_GROUP')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_GROUP DROP CONSTRAINT IX_objQual_GROUP;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: IX_objQual_Rank
IF (EXISTS(SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='IX_objQual_RANK')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_RANK DROP CONSTRAINT IX_objQual_RANK;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: IX_objQual_Smiley
IF (EXISTS(SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='IX_objQual_SMILEY')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_SMILEY DROP CONSTRAINT IX_objQual_SMILEY;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: IX_objQual_User
IF (EXISTS(SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='IX_objQual_USER')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_USER DROP CONSTRAINT IX_objQual_USER';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: IX_objQual_WatchForum
IF (EXISTS(SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='IX_objQual_WATCHFORUM')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_WATCHFORUM DROP CONSTRAINT IX_objQual_WATCHFORUM;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source primary key: PRIMARY
IF (EXISTS(SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PK_objQual_BOARDID')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_BOARD DROP CONSTRAINT PK_objQual_BOARDID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: IX_objQual_WatchTopic
IF (EXISTS(SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='IX_objQual_WATCHTOPIC')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_WATCHTOPIC DROP CONSTRAINT IX_objQual_WATCHTOPIC;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: PK_objQual_THANKS_THANKSID
IF (EXISTS(SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PK_objQual_THANKS_THANKSID')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_THANKS DROP CONSTRAINT PK_objQual_THANKS_THANKSID;';
END
--GO


EXECUTE BLOCK
AS
BEGIN
-- Source unique key: PK_objQual_BUDDY_BUDDYID
IF (EXISTS(SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PK_objQual_BUDDY_BUDDYID')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_BUDDY DROP CONSTRAINT PK_objQual_BUDDY_BUDDYID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: PK_objQual_BUDDY_BUDDYID
IF (EXISTS(SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PK_objQual_FAVORITETOPIC_ID')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_BUDDY DROP CONSTRAINT PK_objQual_FAVORITETOPIC_ID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source unique key: PK_objQual_BUDDY_BUDDYID
IF (EXISTS(SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PK_objQual_POLLGROUPCLUSTER')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_POLLGROUPCLUSTER DROP CONSTRAINT PK_objQual_POLLGROUPCLUSTER;';
END
--GO



