
/* Yet Another Forum.NET Firebird data layer by vzrus
 * Copyright (C) 2006-2012 Vladimir Zakharov
 * https://github.com/vzrus
 * http://sourceforge.net/projects/yaf-datalayers/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2 only
 * General class structure is based on MS SQL Server code,
 * created by YAF developers
 *
 * http://www.yetanotherforum.net/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation;version 2 only
 * of the License.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_DBINFO_TABLE_COLUMNS_INFO')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_DBINFO_TABLE_COLUMNS_INFO;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_SAVESTYLE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_SAVESTYLE;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_SAVENOTIFICATION')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_SAVENOTIFICATION;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_MAXID')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_MAXID;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_UNANSWERED')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_UNANSWERED;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_UPDATE_SSN_STATUS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_UPDATE_SSN_STATUS;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ANNOUNCEMENTS_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ANNOUNCEMENTS_LIST;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ACCESSMASK_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ACCESSMASK_DELETE;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_THANKFROMCOUNT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_THANKFROMCOUNT;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_REPLIEDTOPIC')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_REPLIEDTOPIC;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ADMIN_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ADMIN_LIST;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ACCESSMASK_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ACCESSMASK_LIST;';  
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ACCESSMASK_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ACCESSMASK_SAVE;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ACTIVE_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ACTIVE_LIST;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ACTIVE_LIST_USER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ACTIVE_LIST_USER;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ACTIVE_LISTFORUM')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ACTIVE_LISTFORUM;';  
END

--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ACTIVE_LISTTOPIC')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ACTIVE_LISTTOPIC;';  
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ACTIVE_STATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ACTIVE_STATS;';  
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ATTACHMENT_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ATTACHMENT_DELETE;';  
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ATTACHMENT_DOWNLOAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ATTACHMENT_DOWNLOAD;';  
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ATTACHMENT_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ATTACHMENT_LIST;';  
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ATTACHMENT_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ATTACHMENT_SAVE;';  
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BANNEDIP_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BANNEDIP_DELETE;';  
END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BANNEDIP_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BANNEDIP_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BANNEDIP_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BANNEDIP_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BBCODE_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BBCODE_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BBCODE_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BBCODE_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BBCODE_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BBCODE_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BOARD_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BOARD_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BOARD_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BOARD_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BOARD_POSTSTATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BOARD_POSTSTATS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BOARD_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BOARD_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BOARD_STATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BOARD_STATS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BOARD_RESYNC')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BOARD_RESYNC;';  END
--GO





EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_REGISTRY_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_REGISTRY_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BOARD_CREATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BOARD_CREATE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_SYSTEM_UPDATEVERSION')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_SYSTEM_UPDATEVERSION;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_SYSTEM_INITIALIZE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_SYSTEM_INITIALIZE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_RESYNC')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_RESYNC;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_EVENTLOG_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_EVENTLOG_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_EXTENSION_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_EXTENSION_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_EXTENSION_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_EXTENSION_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_PAGELOAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_PAGELOAD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_REGISTRY_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_REGISTRY_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_MODERATORS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_MODERATORS;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MODERATORS_TEAM_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MODERATORS_TEAM_LIST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_CATEGORY_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_CATEGORY_LIST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_LISTREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_LISTREAD;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_LISTREAD_HELPER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_LISTREAD_HELPER;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_LATEST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_LATEST;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_GUEST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_GUEST;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_LISTPATH')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_LISTPATH;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_LIST;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_CATEGORY_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_CATEGORY_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_CATEGORY_LISTREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_CATEGORY_LISTREAD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_CATEGORY_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_CATEGORY_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_CATEGORY_SIMPLELIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_CATEGORY_SIMPLELIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_CHECKEMAIL_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_CHECKEMAIL_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_CHECKEMAIL_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_CHECKEMAIL_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_CHECKEMAIL_UPDATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_CHECKEMAIL_UPDATE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_CHOICE_ADD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_CHOICE_ADD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_CHOICE_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_CHOICE_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_CHOICE_UPDATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_CHOICE_UPDATE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_CHOICE_VOTE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_CHOICE_VOTE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_EVENTLOG_CREATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_EVENTLOG_CREATE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_EVENTLOG_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_EVENTLOG_DELETE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_EXTENSION_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_EXTENSION_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_EXTENSION_EDIT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_EXTENSION_EDIT;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_LISTALL')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_LISTALL;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_LISTALL_FROMCAT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_LISTALL_FROMCAT;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_LISTALLMYMODERATED')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_LISTALLMYMODERATED;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_LISTSUBFORUMS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_LISTSUBFORUMS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_LISTTOPICS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_LISTTOPICS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_MODERATELIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_MODERATELIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_SIMPLELIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_SIMPLELIST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUMACCESS_GROUP')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUMACCESS_GROUP;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUMACCESS_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUMACCESS_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUMACCESS_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUMACCESS_SAVE;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_GROUP_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_GROUP_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_GROUP_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_GROUP_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_GROUP_MEDAL_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_GROUP_MEDAL_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_GROUP_MEDAL_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_GROUP_MEDAL_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_GROUP_MEMBER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_GROUP_MEMBER;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_GROUP_MEDAL_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_GROUP_MEDAL_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_GROUP_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_GROUP_SAVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_GROUP_RANK_STYLE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_GROUP_RANK_STYLE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MAIL_CREATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MAIL_CREATE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MAIL_CREATEWATCH')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MAIL_CREATEWATCH;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MAIL_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MAIL_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MAIL_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MAIL_LIST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MEDAL_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MEDAL_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MEDAL_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MEDAL_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MEDAL_LISTUSERS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MEDAL_LISTUSERS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MEDAL_RESORT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MEDAL_RESORT;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MEDAL_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MEDAL_SAVE;';  END
--GO








EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_DELETEUNDELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_DELETEUNDELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_FINDUNREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_FINDUNREAD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_GETREPLIES')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_GETREPLIES;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_LISTREPORTED')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_LISTREPORTED;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_LISTREPORTERS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_LISTREPORTERS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_MOVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_MOVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_REPLY_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_REPLY_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_REPORT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_REPORT;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_REPORTCOPYOVER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_REPORTCOPYOVER;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_REPORTRESOLVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_REPORTRESOLVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_SIMPLELIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_SIMPLELIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_UNAPPROVED')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_UNAPPROVED;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_UPDATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_UPDATE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_NNTPFORUM_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_NNTPFORUM_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_NNTPFORUM_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_NNTPFORUM_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_NNTPFORUM_UPDATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_NNTPFORUM_UPDATE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_NNTPSERVER_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_NNTPSERVER_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_NNTPSERVER_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_NNTPSERVER_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_NNTPSERVER_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_NNTPSERVER_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_NNTPTOPIC_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_NNTPTOPIC_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_NNTPTOPIC_SAVEMESSAGE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_NNTPTOPIC_SAVEMESSAGE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_PMESSAGE_ARCHIVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_PMESSAGE_ARCHIVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_PMESSAGE_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_PMESSAGE_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_PMESSAGE_INFO')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_PMESSAGE_INFO;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_PMESSAGE_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_PMESSAGE_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_PMESSAGE_MARKREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_PMESSAGE_MARKREAD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_PMESSAGE_PRUNE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_PMESSAGE_PRUNE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_PMESSAGE_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_PMESSAGE_SAVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_POLL_REMOVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_POLL_REMOVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_POLL_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_POLL_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_POLL_STATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_POLL_STATS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_POLL_UPDATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_POLL_UPDATE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_POLLVOTE_CHECK')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_POLLVOTE_CHECK;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_POST_LAST10USER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_POST_LAST10USER;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_POST_ALLUSER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_POST_ALLUSER;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_POST_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_POST_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_POST_LIST_REVERSE10')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_POST_LIST_REVERSE10;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_RANK_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_RANK_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_RANK_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_RANK_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_RANK_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_RANK_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_REPLACE_WORDS_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_REPLACE_WORDS_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_REPLACE_WORDS_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_REPLACE_WORDS_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_REPLACE_WORDS_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_REPLACE_WORDS_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_RSSTOPIC_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_RSSTOPIC_LIST;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_SMILEY_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_SMILEY_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_SMILEY_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_SMILEY_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_SMILEY_LISTUNIQUE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_SMILEY_LISTUNIQUE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_SMILEY_RESORT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_SMILEY_RESORT;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_SMILEY_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_SMILEY_SAVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_ACTIVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_ACTIVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_UNREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_UNREAD;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_ANNOUNCEMENTS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_ANNOUNCEMENTS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_CREATE_BY_MESSAGE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_CREATE_BY_MESSAGE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_FINDNEXT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_FINDNEXT;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_FINDPREV')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_FINDPREV;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_INFO')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_INFO;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_LISTMESSAGES')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_LISTMESSAGES;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_LOCK')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_LOCK;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_MOVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_MOVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_POLL_UPDATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_POLL_UPDATE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_PRUNE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_PRUNE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_SIMPLELIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_SIMPLELIST;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_ACCESSMASKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_ACCESSMASKS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_ACTIVITY_RANK')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_ACTIVITY_RANK;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_ADDIGNOREDUSER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_ADDIGNOREDUSER;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_ADDPOINTS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_ADDPOINTS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='USER_REMOVEPOINTS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE USER_REMOVEPOINTS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_ADMINSAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_ADMINSAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_APPROVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_APPROVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_APPROVEALL')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_APPROVEALL;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_ASPNET')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_ASPNET;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_AVATARIMAGE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_AVATARIMAGE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_CHANGEPASSWORD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_CHANGEPASSWORD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_DELETEAVATAR')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_DELETEAVATAR;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_DELETEOLD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_DELETEOLD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_EMAILS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_EMAILS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_FIND')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_FIND;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_GET')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_GET;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_GETPOINTS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_GETPOINTS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_GETSIGNATURE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_GETSIGNATURE;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_REMOVEIGNOREDUSER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_REMOVEIGNOREDUSER;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_ISUSERIGNORED')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_ISUSERIGNORED;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_LASTREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_LASTREAD;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_LIST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_LIST_OLD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_LIST_OLD;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_LISTMEDALS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_LISTMEDALS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_LOGIN')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_LOGIN;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_MEDAL_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_MEDAL_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_MEDAL_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_MEDAL_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_MEDAL_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_MEDAL_SAVE;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_MIGRATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_MIGRATE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_NNTP')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_NNTP;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_PMCOUNT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_PMCOUNT;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_RECOVERPASSWORD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_RECOVERPASSWORD;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_REMOVEPOINTS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_REMOVEPOINTS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_REMOVEPOINTSBYTOPICID')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_REMOVEPOINTSBYTOPICID;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_RESETPOINTS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_RESETPOINTS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_SAVEAVATAR')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_SAVEAVATAR;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_SAVEPASSWORD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_SAVEPASSWORD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_SAVESIGNATURE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_SAVESIGNATURE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_SETNOTDIRTY')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_SETNOTDIRTY;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_SETPOINTS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_SETPOINTS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_SETROLE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_SETROLE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_SIMPLELIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_SIMPLELIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_SUSPEND')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_SUSPEND;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_THANKFROMCOUNT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_THANKFROMCOUNT;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USERREPLIEDTOPIC')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USERREPLIEDTOPIC;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USERFORUM_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USERFORUM_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USERFORUM_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USERFORUM_SAVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USERGROUP_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USERGROUP_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USERGROUP_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USERGROUP_SAVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USERPMESSAGE_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USERPMESSAGE_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USERPMESSAGE_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USERPMESSAGE_LIST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_WATCHFORUM_ADD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_WATCHFORUM_ADD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_WATCHFORUM_CHECK')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_WATCHFORUM_CHECK;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_WATCHFORUM_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_WATCHFORUM_LIST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_WATCHTOPIC_ADD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_WATCHTOPIC_ADD;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_WATCHTOPIC_CHECK')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_WATCHTOPIC_CHECK;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_WATCHTOPIC_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_WATCHTOPIC_LIST;';  END
--GO


--Dependencies

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ACTIVE_UPDATEMAXSTATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ACTIVE_UPDATEMAXSTATS;';  END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_DELETE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_MOVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_MOVE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_NNTPFORUM_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_NNTPFORUM_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USERFORUM_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USERFORUM_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_WATCHFORUM_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_WATCHFORUM_DELETE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_WATCHTOPIC_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_WATCHTOPIC_DELETE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_UPDATELASTPOST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_UPDATELASTPOST;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_UPDATELASTPOST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_UPDATELASTPOST;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_APPROVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_APPROVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_SAVE;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_FORUM_UPDATESTATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_FORUM_UPDATESTATS;';  END
--GO
EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_UPGRADE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_UPGRADE;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_VACCESS_UL')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_VACCESS_UL;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_VACCESS_ULF')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_VACCESS_ULF;';  END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_IGNOREDLIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_IGNOREDLIST;';  
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_SHOUTBOX_GETMESSAGES')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_SHOUTBOX_GETMESSAGES;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_SHOUTBOX_SAVEMESSAGE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_SHOUTBOX_SAVEMESSAGE;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_SHOUTBOX_CLEARMESSAGES')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_SHOUTBOX_CLEARMESSAGES;';  
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_DB_SIZE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_DB_SIZE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_ADDTHANKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_ADDTHANKS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_GETTHANKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_GETTHANKS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_ISTHANKEDBYUSER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_ISTHANKEDBYUSER';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_MESSAGE_GETALLTHANKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_GETALLTHANKS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_REMOVETHANKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_REMOVETHANKS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_REMOVETHANKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_REMOVETHANKS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_THANKSNUMBER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_THANKSNUMBER';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_GETTHANKS_FROM')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_GETTHANKS_FROM';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_GETTHANKS_TO')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_GETTHANKS_TO';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_GETALLTHANKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_GETALLTHANKS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BUDDY_ADDREQUEST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BUDDY_ADDREQUEST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BUDDY_APPROVEREQUEST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BUDDY_APPROVEREQUEST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BUDDY_DENYREQUEST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BUDDY_DENYREQUEST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BUDDY_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BUDDY_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BUDDY_REMOVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BUDDY_REMOVE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_FAVORITE_ADD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_FAVORITE_ADD';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_FAVORITE_REMOVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_FAVORITE_REMOVE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_FAVORITE_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_FAVORITE_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_FAVORITE_DETAILS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_FAVORITE_DETAILS';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ALBUM_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ALBUM_SAVE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ALBUM_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ALBUM_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ALBUM_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ALBUM_DELETE';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ALBUM_GETTITLE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ALBUM_GETTITLE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ALBUM_GETSTATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ALBUM_GETSTATS';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ALBUM_IMAGE_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ALBUM_IMAGE_SAVE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ALBUM_IMAGE_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ALBUM_IMAGE_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ALBUM_IMAGES_BYUSER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ALBUM_IMAGES_BYUSER';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ALBUM_IMAGE_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ALBUM_IMAGE_DELETE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ALBUM_IMAGE_DOWNLOAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ALBUM_IMAGE_DOWNLOAD';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_GETSIGNATUREDATA')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_GETSIGNATUREDATA';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_GETALBUMSDATA')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_GETALBUMSDATA';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_SECDATA')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_SECDATA';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGEHISTORY_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGEHISTORY_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ACTIVE_LIST_USER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ACTIVE_LIST_USER';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_VIEWALLTHANKS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_VIEWALLTHANKS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_LAZYDATA')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_LAZYDATA';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_LISTMEMBERS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_LISTMEMBERS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_MESSAGE_GETTEXTBYIDS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_MESSAGE_GETTEXTBYIDS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BOARD_USERSTATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BOARD_USERSTATS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_RSS_TOPIC_LATEST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_RSS_TOPIC_LATEST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_FINDDUPLICATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_FINDDUPLICATE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_POLLGROUP_STATS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_POLLGROUP_STATS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_POLLGROUP_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_POLLGROUP_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_POLLGROUP_ATTACH')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_POLLGROUP_ATTACH';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_POLLGROUP_VOTECHECK')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_POLLGROUP_VOTECHECK';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_POLLGROUP_REMOVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_POLLGROUP_REMOVE';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPIC_FAVORITE_COUNT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPIC_FAVORITE_COUNT';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPICS_BYUSER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPICS_BYUSER';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_READTOPIC_ADDORUPDATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_READTOPIC_ADDORUPDATE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_READTOPIC_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_READTOPIC_DELETE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_READTOPIC_LASTREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_READTOPIC_LASTREAD';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_READFORUM_ADDORUPDATE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_READFORUM_ADDORUPDATE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_READFORUM_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_READFORUM_DELETE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_READFORUM_LASTREAD')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_READFORUM_LASTREAD';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_RECENT_USERS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_RECENT_USERS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_THANKEDMESSAGE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_THANKEDMESSAGE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ACTIVEACCESS_RESET')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ACTIVEACCESS_RESET';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_BOARD_SETGUIG')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_BOARD_SETGUIG';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ADMIN_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ADMIN_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_LISTMEMBERS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_LISTMEMBERS';
END
--GO



EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPICSTATUS_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPICSTATUS_DELETE';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPICSTATUS_EDIT')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPICSTATUS_EDIT';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPICSTATUS_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPICSTATUS_LIST';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_TOPICSTATUS_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_TOPICSTATUS_SAVE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_USER_UPDATEFACEBOOKSTATUS')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_USER_UPDATEFACEBOOKSTATUS';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_DBINFO_TABLE_COLUMNS_INFO')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_DBINFO_TABLE_COLUMNS_INFO';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ALBUM_IMAGES_BY_USER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ALBUM_IMAGES_BY_USER';
END
--GO


EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ADMINPAGEACCESS_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ADMINPAGEACCESS_SAVE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ADMINPAGEACCESS_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ADMINPAGEACCESS_DELETE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ADMINPAGEACCESS_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ADMINPAGEACCESS_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_ADMIN_PAGEACCESSLIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_ADMIN_PAGEACCESSLIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_EVENTLOGGROUPACCESS_SAVE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_EVENTLOGGROUPACCESS_SAVE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_EVENTLOGGROUPACCESS_DELETE')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_EVENTLOGGROUPACCESS_DELETE';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_EVENTLOGGROUPACCESS_LIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_EVENTLOGGROUPACCESS_LIST';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_EVENTLOG_DELETEBYUSER')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_EVENTLOG_DELETEBYUSER';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (EXISTS(SELECT FIRST 1 1 
FROM RDB$PROCEDURES a WHERE a.RDB$PROCEDURE_NAME='objQual_GROUP_EVENTLOGACCESSLIST')) THEN
EXECUTE STATEMENT 'DROP PROCEDURE objQual_GROUP_EVENTLOGACCESSLIST';
END
--GO





