/* Yet Another Forum.NET Firebird data layer by vzrus
 * Copyright (C) 2006-2012 Vladimir Zakharov
 * https://github.com/vzrus
 * http://sourceforge.net/projects/yaf-datalayers/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2 only
 * General class structure is based on MS SQL Server code,
 * created by YAF developers
 *
 * http://www.yetanotherforum.net/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation;version 2 only
 * of the License.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_ACCESSMASK_ACCESSMASKID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_ACCESSMASK_ACCESSMASKID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_ATTACHMENT_ATTACHMENTID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_ATTACHMENT_ATTACHMENTID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_BANNEDIP_ID' 
                       AND a.RDB$SYSTEM_FLAG =0  ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_BANNEDIP_ID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_BBCODE_BBCODEID' 
                       AND a.RDB$SYSTEM_FLAG =0  ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_BBCODE_BBCODEID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_BOARD_BOARDID' 
                       AND a.RDB$SYSTEM_FLAG =0  ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_BOARD_BOARDID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_CATEGORY_CATEGORYID' 
                  AND a.RDB$SYSTEM_FLAG =0  ROWS 1)) THEN
    EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_CATEGORY_CATEGORYID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_CHECKEMAIL_CHECKEMAILID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_CHECKEMAIL_CHECKEMAILID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_CHOICE_CHOICEID' 
                     AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_CHOICE_CHOICEID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_EVENTLOG_EVENTLOGID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_EVENTLOG_EVENTLOGID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_EXTENSION_EXTENSIONID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_EXTENSION_EXTENSIONID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1
                     FROM RDB$GENERATORS a
					 WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_FORUM_FORUMID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_FORUM_FORUMID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_GROUP_GROUPID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_GROUP_GROUPID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_MAIL_MAILID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_MAIL_MAILID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_MEDAL_MEDALID' 
                  AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
   EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_MEDAL_MEDALID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_MESSAGE_MESSAGEID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_MESSAGE_MESSAGEID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_MESSAGE_LOGID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_MESSAGE_LOGID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_NNTPFORUM_NNTPFORUMID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_NNTPFORUM_NNTPFORUMID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_NNTPSERVER_NNTPSERVERID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
        EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_NNTPSERVER_NNTPSERVERID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_NNTPTOPIC_NNTPTOPICID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_NNTPTOPIC_NNTPTOPICID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_PMESSAGE_PMESSAGEID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
        EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_PMESSAGE_PMESSAGEID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_POLLGC_POLLGROUPID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_POLLGC_POLLGROUPID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_POLL_POLLID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_POLL_POLLID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_POLLVOTE_POLLVOTEID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_POLLVOTE_POLLVOTEID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_RANK_RANKID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_RANK_RANKID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_REGISTRY_REGISTRYID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_REGISTRY_REGISTRYID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_REPLACE_WORDS_ID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_REPLACE_WORDS_ID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_SMILEY_SMILEYID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_SMILEY_SMILEYID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_TOPIC_TOPICID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_TOPIC_TOPICID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_USER_USERID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_USER_USERID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_USERPME_USERPMESSAGEID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_USERPME_USERPMESSAGEID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_WATCHFORUM_WATCHFORUMID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_WATCHFORUM_WATCHFORUMID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_WATCHTOPIC_WATCHTOPICID' 
                  AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
    EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_WATCHTOPIC_WATCHTOPICID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_SBOXMESG_SBOXMESGID' 
                  AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
    EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_SBOXMESG_SBOXMESGID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_THANKS_THANKSID' 
                  AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
    EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_THANKS_THANKSID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_BUDDY_ID' 
                  AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
    EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_BUDDY_ID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_FAVORITETOPIC_ID' 
                  AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
    EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_FAVORITETOPIC_ID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_USERALBUM_ALBUMID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_USERALBUM_ALBUMID;';
END
--GO


EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_USRALBIMG_IMAGEID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_USRALBIMG_IMAGEID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_MSGHIS_MSGHISID' 
                     AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_MSGHIS_MSGHISID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_PGC_POLLGROUPID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_PGC_POLLGROUPID;';
END
--GO

EXECUTE BLOCK
AS
BEGIN
     IF (NOT EXISTS (SELECT 1 FROM RDB$GENERATORS a 
                     WHERE a.RDB$GENERATOR_NAME='SEQ_objQual_TOPSTATUS_TOPSTID' 
                       AND a.RDB$SYSTEM_FLAG =0 ROWS 1)) THEN
         EXECUTE STATEMENT 'CREATE SEQUENCE SEQ_objQual_TOPSTATUS_TOPSTID;';
END
--GO





