/* Yet Another Forum.NET MySQL data layer by vzrus
 * Copyright (C) 2006-2012 Vladimir Zakharov
 * https://github.com/vzrus
 * http://sourceforge.net/projects/yaf-datalayers/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; version 2 only
 * General class structure is based on MS SQL Server code,
 * created by YAF developers
 *
 * http://www.yetanotherforum.net/
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation;version 2 only
 * of the License.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

CREATE PROCEDURE DP_DROP_SEQUENCE
  (GENAME VARCHAR(32))
AS
BEGIN
  IF (EXISTS(
    SELECT 1 FROM RDB$GENERATORS
    WHERE UPPER(RDB$GENERATOR_NAME) = UPPER(:GENAME) 
  )) THEN
  EXECUTE STATEMENT 'DROP SEQUENCE "' || UPPER(:GENAME) || '"';  
END;
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_ACCESSMASK_ACCESSMASKID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_ATTACHMENT_ATTACHMENTID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_BANNEDIP_ID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_BBCODE_BBCODEID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_BOARD_BOARDID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_CATEGORY_CATEGORYID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_CHECKEMAIL_CHECKEMAILID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_CHOICE_CHOICEID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_EVENTLOG_EVENTLOGID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_EXTENSION_EXTENSIONID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_FORUM_FORUMID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_GROUP_GROUPID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_MAIL_MAILID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_MEDAL_MEDALID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_MESSAGE_MESSAGEID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_MESSAGE_LOGID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_NNTPFORUM_NNTPFORUMID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_NNTPSERVER_NNTPSERVERID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_NNTPTOPIC_NNTPTOPICID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_PMESSAGE_PMESSAGEID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_POLLGC_POLLGROUPID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_POLL_POLLID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_POLLVOTE_POLLVOTEID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_RANK_RANKID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_REGISTRY_REGISTRYID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_REPLACE_WORDS_ID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_SMILEY_SMILEYID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_TOPIC_TOPICID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_USER_USERID');
--GO                                
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_USERPME_USERPMESSAGEID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_WATCHFORUM_WATCHFORUMID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_WATCHTOPIC_WATCHTOPICID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_THANKS_THANKSID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_BUDDY_ID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_USERALBUM_ALBUMID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_USRALBIMG_IMAGEID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_MSGHIS_MSGHISID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_PGC_POLLGROUPID');
--GO
EXECUTE PROCEDURE DP_DROP_SEQUENCE('SEQ_objQual_TOPSTATUS_TOPSTID');
--GO
DROP PROCEDURE DP_DROP_SEQUENCE;
--GO