-- Drop  indexes  if exist.

EXECUTE BLOCK
AS
BEGIN
-- Source Index: IX_objQual_P_ROLE_APPLICA
IF (EXISTS (SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME='IX_objQual_P_ROLE_APPLICA')) THEN
EXECUTE STATEMENT 'DROP INDEX IX_objQual_P_ROLE_APPLICA';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source Index: IX_objQual_P_ROLEMEMBERSHIPip_Role
IF (EXISTS (SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME='IX_objQual_P_ROLEMEMBERSHIP')) THEN
EXECUTE STATEMENT 'DROP INDEX IX_objQual_P_ROLEMEMBERSHIP';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source Index: IX_objQual_P_ROLEMEMBERSHIP1
IF (EXISTS (SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME='IX_objQual_P_ROLEMEMBERSHIP1')) THEN
EXECUTE STATEMENT 'DROP INDEX IX_objQual_P_ROLEMEMBERSHIP1';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source Index: IX_objQual_P_ROLE_NAME
IF (EXISTS (SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME='IX_objQual_P_ROLE_NAME')) THEN
EXECUTE STATEMENT 'DROP INDEX IX_objQual_P_ROLE_NAME';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source Index: IX_objQual_P_APPLICATION_Name
IF (EXISTS (SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME='IX_objQual_P_APPLICATION_')) THEN
EXECUTE STATEMENT 'DROP INDEX IX_objQual_P_APPLICATION_';
END
--GO

EXECUTE BLOCK
AS
BEGIN
-- Source Index: IX_objQual_P_MEMBERSHIP_APPpplicat
IF (EXISTS (SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME='IX_objQual_P_MEMBERSHIP_APP')) THEN
EXECUTE STATEMENT 'DROP INDEX IX_objQual_P_MEMBERSHIP_APP';
END
--GO
EXECUTE BLOCK
AS
BEGIN
-- Source Index: IX_objQual_P_MEMBERSHIP_Username
IF (EXISTS (SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME='IX_objQual_P_MEMBERSHIP_U')) THEN
EXECUTE STATEMENT 'DROP INDEX IX_objQual_P_MEMBERSHIP_U';
END
--GO
EXECUTE BLOCK
AS
BEGIN
-- Source Index: IX_objQual_P_MEMBERSHIP_Email
IF (EXISTS (SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME='IX_objQual_P_MEMBERSHIP_E')) THEN
EXECUTE STATEMENT 'DROP INDEX IX_objQual_P_MEMBERSHIP_E';
END
--GO






















