-- Source primary key: PRIMARY
EXECUTE BLOCK
AS
BEGIN 
-- Source primary key: PRIMARY
IF (NOT EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY025')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_P_APPLICATION ADD CONSTRAINT PRIMARY025 PRIMARY KEY (APPLICATIONID);';
END
--GO
-- Source primary key: PRIMARY
EXECUTE BLOCK
AS
BEGIN 
-- Source primary key: PRIMARY
IF (NOT EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY026')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_P_MEMBERSHIP ADD CONSTRAINT PRIMARY026 PRIMARY KEY (USERID);';
END
--GO
EXECUTE BLOCK
AS
BEGIN 
-- Source primary key: PRIMARY
IF (NOT EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY027')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_P_PROFILE ADD CONSTRAINT PRIMARY027 PRIMARY KEY (USERID);';
END
--GO

EXECUTE BLOCK
AS
BEGIN 
-- Source primary key: PRIMARY
IF (NOT EXISTS( SELECT 1
FROM RDB$INDICES a WHERE a.RDB$INDEX_NAME ='PRIMARY028')) THEN
EXECUTE STATEMENT 'ALTER TABLE objQual_P_ROLE ADD CONSTRAINT PRIMARY028 PRIMARY KEY (ROLEID);';
END
--GO