-- Drop all primary keys if exist.

CREATE PROCEDURE DP_DROP_PKEY_PROC
  (KEYTYPE VARCHAR(50),  TABLENAME VARCHAR(50), KEYNAME VARCHAR(50),CN1 VARCHAR(50),CN2 VARCHAR(50))
AS
BEGIN
  IF (EXISTS(
    SELECT 1 FROM RDB$RELATION_CONSTRAINTS R
    WHERE (R.RDB$CONSTRAINT_NAME = :KEYNAME) AND (R.RDB$RELATION_NAME = :TABLENAME)
        AND (R.RDB$CONSTRAINT_TYPE = :KEYTYPE)
  )) THEN
  EXECUTE STATEMENT 'ALTER TABLE ' || :TABLENAME || ' DROP CONSTRAINT ' || :KEYNAME || ';';
END;
--GO

-- Source primary key: PRIMARY
EXECUTE PROCEDURE DP_DROP_PKEY_PROC('PRIMARY KEY','objQual_PROV_APPLICATION', 'PRIMARY025','ApplicationID','');
--GO

-- Source primary key: PRIMARY
EXECUTE PROCEDURE DP_DROP_PKEY_PROC('PRIMARY KEY','objQual_PROV_MEMBERSHIP', 'PRIMARY026','UserID','');
--GO



-- Source primary key: PRIMARY
EXECUTE PROCEDURE DP_DROP_PKEY_PROC('PRIMARY KEY','objQual_PROV_PROFILE', 'PRIMARY027','UserID','');
--GO

-- Source unique key: PRIMARY
EXECUTE PROCEDURE DP_DROP_PKEY_PROC('PRIMARY KEY','objQual_PROV_ROLE', 'PRIMARY028','RoleID','');
--GO


DROP PROCEDURE DP_DROP_PKEY_PROC;
--GO